spring:
  liquibase:
    change-log: classpath:/liquibase-changelog.xml
  datasource:
    url: jdbc:mysql://localhost:3307/mechanic
    username: user
    password: password
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true

app:
  repair:
    priceForOneWorkHour: 100.00
    maximumRepairPerDay: 3

scheduling:
  enabled: true